### ISSUE TITLE
Last 4 or 5 Versions of CHIRP have not worked!  last working version was 20240410

### ISSUE THREAD

**Issue by leirbag28** [goldstar611/chirp#11]
I don't know if this is an Appimage ONLY issue or perhaps even though i am using the Appimage version, the problem may be in this version before its packed as Appimage?:
(Using Ubuntu 18.04.6 MATE and someone mentioned it has same exact issue on Gentoo):

Dropped the Appimage into terminal and get this error:

Traceback (most recent call last):
  File "/tmp/.mount_Chirp-PgXjf9/usr/bin/chirp", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/tmp/.mount_Chirp-PgXjf9/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3254, in <module>
    def _initialize_master_working_set():
  File "/tmp/.mount_Chirp-PgXjf9/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3237, in _call_aside
    f(*args, **kwargs)
  File "/tmp/.mount_Chirp-PgXjf9/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3266, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/tmp/.mount_Chirp-PgXjf9/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 584, in _build_master
    ws.require(__requires__)
  File "/tmp/.mount_Chirp-PgXjf9/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 901, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/tmp/.mount_Chirp-PgXjf9/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 787, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'suds' distribution was not found and is required by chirp

PLEAS PLEASE fix.

**Comment by leirbag28** [comment]
The Appimage version was the only hope of many of us even being able to use CHIRP as the regular install version requires updating Python which will ruin all my other Python reliant apps. Since tue Appimage is all self contained it justvworks as a Drag and Drop and just click to open as you already know. This type of app is definitely better as an Appimage.I hope you will reconsider continuing to package it that way.Sent from my iPhoneOn Jan 2, 2025, at 10:00 PM, goldstar611 ***@***.***> wrote:﻿
Closed #11 as completed.
